### ISSUE TITLE
How to setup device_id parameter with two ISS channels

### ISSUE THREAD

**Issue by dhover** [Drealine/weatherlinklive-driver-weewx#1]
I have a Davis Weatherlink Live with 2 devices connected. The first one is an ISS without wind meter and the second one is the Wind meter connected by a Davis 6332 sensor transmitter kit. The WLL is configured with ISS on channel 1 and the Wind meter on channel 2. This is a normal configuration if the wind meter is located on another location as the iss. 

I configured device_id = 1:iss-2:iss but then the values from channels 1 (temp, hum) are overwritten by those of the second channel which do not contain those values. The wind values are shown ok. 
Tried with device_id = 2:iss-1:iss but then the wind values are overwritten by the empty values from channel 1.
How the setup the device_id parameter in this situation?

**Comment by Drealine** [comment]
Hi,

At the moment, the only thing to do that is to put this on your conf : 

`device_id = 1:iss-2:extra_Anenometer`. It overwritten winds values from the ISS and not others values.

Be carefull because it is not implemented to get lost data from Weatherlink.com. I will work on it soon to add sensors which are not connected to the ISS. 

Let me know. 

-fp

**Comment by Drealine** [comment]
Hi,

The only thing to do that at the moment is to set this : 

`device_id = 1:iss-2:extra_Anenometer`

It will be overwritten only winds values and not others values like you mentioned.

It is not implemented to get lost data from Weatherlink.com. Keep an eye to this thread, I will work on it to implement. 

Let me know if it work.
-fp

**Comment by dhover** [comment]
> The only thing to do that at the moment is to set this :
> 
> `device_id = 1:iss-2:extra_Anenometer`
Ok, that works.
In the source code there is a small typo  extra_Anenometer    should be    extra_Anemometer

> It is not implemented to get lost data from Weatherlink.com. Keep an eye to this thread, I will work on it to implement.
After a restart I indeed got a lot of errors because I didn't changed the default Weatherlink.com parameters.
Is it possible to disable the use of Weatherlink.com for data retrieval?

**Comment by Drealine** [comment]
Thank's. I will push a new update next week. 
Not at the moment.  It is one of possibility. I will work on it also.

**Comment by Drealine** [comment]
Updated the repo to include enable or disable wl archive.
