### ISSUE TITLE
Logging Enabled?

### ISSUE THREAD

**Issue by gary-hammer** [Drealine/weatherlinklive-driver-weewx#13]
I've installed your driver and it works a treat with my WLL and Anemometer transmitter.
My problem is, the packets are being logged. As this happens every 2.5 seconds or so, it's a huge amount being written.
I do not have debug enabled in WeeWX.
How can I stop this driver from logging?

See attached file logging_example.txt

[logging_example.txt](https://github.com/Drealine/weatherlinklive-driver-weewx/files/5402285/logging_example.txt)

**Comment by Drealine** [comment]
Hi.

The driver show all packets received from WLL in syslog.
But it's a good question. I think it's a good idea to show packets only when debug is enabled.

Keep an eye to this thread. I will put an update into the WLLDriver.

**Comment by gary-hammer** [comment]
Thanks, watching the thread.
