### ISSUE TITLE
Error installation version 0.4

### ISSUE THREAD

**Issue by dhover** [Drealine/weatherlinklive-driver-weewx#2]
I got an error installing the lastest version:

`version 0.3.0:
sudo ./bin/wee_extension --install=/home/weewx/WLLDriver.zip
Request to install '/home/weewx/WLLDriver.zip'
Extracting from zip archive /home/weewx/WLLDriver.zip
Saving installer file to /home/weewx/bin/user/installer/WLLDriver
Saved configuration dictionary. Backup copy at /home/weewx/weewx.conf.20200905125026
Finished installing extension '/home/WLLDriver.zip'

version 0.4.0:
sudo ./bin/wee_extension --install=/home/weewx/WLLDriver.zip
Request to install '/home/weewx/WLLDriver.zip'
Extracting from zip archive /home/weewx/WLLDriver.zip
Traceback (most recent call last):
  File "./bin/wee_extension", line 88, in <module>
    main()
  File "./bin/wee_extension", line 80, in main
    ext.install_extension(options.install)
  File "/home/weewx/bin/weecfg/extension.py", line 112, in install_extension
    member_names = weecfg.extract_zip(extension_path,
  File "/home/weewx/bin/weecfg/__init__.py", line 1773, in extract_zip
    with open(path, 'wb') as dest_file:
PermissionError: [Errno 13] Permission denied: '/var/tmp/.gitignore'
`

What went wrong?

**Comment by Drealine** [comment]
Hi,

Thank you for you feedback. It is a wrong zip file. I updated the good zip file.
I've tested and it work.

Let me know if it good for you.
NB : Please not that some parameters has changed, see readme.

**Comment by dhover** [comment]
Now it works again.
Thanks.
