### ISSUE TITLE
Sensor Status

### ISSUE THREAD

**Issue by ghost** [Drealine/weatherlinklive-driver-weewx#20]
Hi - I have just started using WeeWX with a Davis WeatherLink Live connected to a Vantage Pro 2.

Your driver works brilliantly - thank you so much - https://wx-watch.co.uk/weewx

The station is set to update every 5 minutes.

A question if I may. The Sensor Status does not always display correctly - mostly the only info is the Transmitter Battery Status, but sometimes full status is displayed - is there any fix for this.

<img width="389" alt="Screenshot 2020-11-29 at 11 48 34 am" src="https://user-images.githubusercontent.com/75205650/100541141-bf5d0080-3239-11eb-9516-8f0201e3260c.png">
<img width="389" alt="Screenshot 2020-11-29 at 11 50 39 am" src="https://user-images.githubusercontent.com/75205650/100541147-c2f08780-3239-11eb-8b09-be1108732dfd.png">

**Comment by ghost** [comment]
For info this website has been moved to https://longsutton-weather.co.uk

**Comment by Drealine** [comment]
Hi,

Battery info, signal quality are refreshed only each 15min. If you've an archive interval which is set to 5min, some values will be not showing while is not refresh.

-Drealine

**Comment by ghost** [comment]
Hi

Many thanks for your reply - is the 15 minute refresh rate built into your driver or is it built into the Vantage pro?
If I alter my station refresh rate to 15 minutes does it mean it will always display correctly?

Again many thanks

**Comment by Drealine** [comment]
Hi,

No problem. It's a limitation from the API v2 of Weatherlink.com. Nothing to do at the moment..
I've just created an issue on their Github to make an API for retrieve archive records. At the moment, it's not possible, but the WLL module can make do that. I suppose that it favorite their cloud data for historical before our own proper data... That is the choice, but no too good for peoples who doesn't want to pay an additionnal subscription to have more historical data.

-Drealine

**Comment by ghost** [comment]
Many thanks for your quick reply
