### ISSUE TITLE
ERROR user.WLLDriver: Failed attempt 1 of 100 to get loop data

### ISSUE THREAD

**Issue by ddperso** [Drealine/weatherlinklive-driver-weewx#26]
Sometimes, I have an error in syslog, and during this error the screen of website is freezed (about 10s)
Do you have an idea?

Jan 20 22:35:12 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:21 CET (1611178521)
Jan 20 22:35:12 meteo weewx[816] INFO weewx.restx: Wunderground-PWS: Published record 2021-01-20 22:35:00 CET (1611178500)
Jan 20 22:35:12 meteo weewx[816] INFO weewx.restx: CWOP: Published record 2021-01-20 22:35:00 CET (1611178500)
Jan 20 22:35:13 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:23 CET (1611178523)
Jan 20 22:35:14 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:24 CET (1611178524)
Jan 20 22:35:15 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:25 CET (1611178525)
Jan 20 22:35:16 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:26 CET (1611178526)
Jan 20 22:35:17 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:27 CET (1611178527)
Jan 20 22:35:18 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:28 CET (1611178528)
Jan 20 22:35:19 meteo weewx[816] ERROR user.WLLDriver: Failed attempt 1 of 100 to get loop data in genLoopPackets: Error while request HTTP [current_conditions] Error is : HTTPConnectionPool(host='192.168.1.201', port=80): Max retries exceeded with url: /v1/current_conditions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff22685bf28>: Failed to establish a new connection: [Errno 111] Connexion refusée'))
Jan 20 22:35:29 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:41 CET (1611178541)
Jan 20 22:35:30 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:42 CET (1611178542)
Jan 20 22:35:31 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:43 CET (1611178543)
Jan 20 22:35:32 meteo weewx[816] ERROR user.WLLDriver: Failed attempt 1 of 100 to get loop data in genLoopPackets: Error while request HTTP [current_conditions] Error is : HTTPConnectionPool(host='192.168.1.201', port=80): Max retries exceeded with url: /v1/current_conditions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff224d941d0>: Failed to establish a new connection: [Errno 111] Connexion refusée'))
Jan 20 22:35:42 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:55 CET (1611178555)
Jan 20 22:35:43 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:56 CET (1611178556)
Jan 20 22:35:44 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:35:57 CET (1611178557)
Jan 20 22:35:45 meteo weewx[816] ERROR user.WLLDriver: Failed attempt 1 of 100 to get loop data in genLoopPackets: Error while request HTTP [current_conditions] Error is : HTTPConnectionPool(host='192.168.1.201', port=80): Max retries exceeded with url: /v1/current_conditions (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7ff2257f3b70>: Failed to establish a new connection: [Errno 111] Connexion refusée'))
Jan 20 22:35:55 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:10 CET (1611178570)
Jan 20 22:35:56 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:11 CET (1611178571)
Jan 20 22:35:57 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:12 CET (1611178572)
Jan 20 22:35:58 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:13 CET (1611178573)
Jan 20 22:36:00 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:14 CET (1611178574)
Jan 20 22:36:01 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:15 CET (1611178575)
Jan 20 22:36:02 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:17 CET (1611178577)
Jan 20 22:36:03 meteo weewx[816] INFO weewx.restx: MQTT: Published record 2021-01-20 22:36:18 CET (1611178578)

**Comment by Drealine** [comment]
Salut @ddperso,

Cela m'arrive d'avoir la même erreur, le WLL ne supporte pas trop de requêtes, surtout si tu n'utilises pas le realtime avec les paquets UDP.
Je vois que tes paquets MQTT sont publiés toutes les secondes, tu devrais augmenter l'intervalle à 3 secondes, ça sera beaucoup plus stable.

Bien à toi.

**Comment by ddperso** [comment]
OK merci
C'est quoi le realtime UDP ? est-ce mieux ?

Didier

**Comment by Drealine** [comment]
Si ton serveur et ton WLL sont en local, oui tu peux. Tu actives **realtime_enable** dans les options WLLDriver.
Par contre, tu n'auras pu les rafales sous 2min, mais sous 10min, le WLL n'ayant pas cette option de dispo lors de l'activation du **realtime**. 
Quand le **realtime** est actif, je te conseil de mettre un **poll_interval** à 10 secondes environ.
Je te laisse regarder la doc dans le main de mon repo pour les autres subtilités qu'il peut y avoir.

**Comment by ddperso** [comment]
Ok je vais regarder
Bonne soirée
Didier

**Comment by ddperso** [comment]
Salut @drealine

J'ai 2 machines virtuelles  (une de test et l'autre "officielle"), cela me
permet de tester avant
sur la machine "officielle" je suis en http toutes les secondes (peu
d'erreurs WLL)
sur la machine de test je suis en UDP (realtime enabled) (peu d'erreurs
également)
C'est la seule différence entre les 2 machines

J'ai une différence sur la pluie, 4,2 mm ce matin à 00:05 avec UDP et 0 mm
en http (je ne pense pas qu'il ait plu ce matin et 4 mm c'est énorme)
Je suis à jour sur github wwewx et Belchertown (à 2 commits près), ma BD
est mysql

Aurais-tu une idée de ce qui s'est passé ?
[image: http.jpg][image: udp.jpg]

**Comment by Drealine** [comment]
Je t'invite à bien mettre à jour mon driver à cette version : https://github.com/Drealine/weatherlinklive-driver-weewx/releases/tag/2020.12-1
970hPa m'avait remonté la même erreur il y a quelques semaines, depuis cela était corrigé.

**Comment by ddperso** [comment]
ok c'est fait, je n'avais pas vu que j'avais du retard...
Comment fais-tu pour être notifié d'un changement dans ton repo ?

Bon dimanche
Didier

**Comment by Drealine** [comment]
Tu peux cliquer sur "Watch" en haut à droit de mon repo pour recevoir des notifs.
Bien  vérif si tu as activé la notif mails sur ton compte Github
