### ISSUE TITLE
Error while request HTTP

### ISSUE THREAD

**Issue by ghost** [Drealine/weatherlinklive-driver-weewx#29]
Hi - just set up WeeWX using you driver. All is working well but I am seeing these errors

May 31 07:50:36 WeeWX python3[10762]: weewx[10762] ERROR user.WLLDriver: Failed attempt 8 of 20 to get loop data in genLoopPackets: Error while request HTTP [current_conditions] Error is : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
May 31 07:50:56 WeeWX python3[10762]: weewx[10762] ERROR user.WLLDriver: Failed attempt 9 of 20 to get loop data in genLoopPackets: Error while request HTTP [current_conditions] Error is : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
May 31 07:51:16 WeeWX python3[10762]: weewx[10762] ERROR user.WLLDriver: Failed attempt 10 of 20 to get loop data in genLoopPackets: Error while request HTTP [current_conditions] Error is : ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

These are the settings I have in my weewx.conf file

[WLLDriver]
    driver = user.WLLDriver
    max_tries = 20
    retry_wait = 20
    poll_interval = 10
    realtime_enable = 0
    hostname = 192.168.1.138
    time_out = 10
    device_id = iss:1
    wl_archive_enable = 1
    wl_apikey = MYAPIKEY
    wl_apisecret = MYAPISECRET
    wl_stationid = MYSTATIONID
    wl_archive_interval = 15

I have loop_on_init = True

Any advice please??

**Comment by Drealine** [comment]
Hi @JansonBHong 
Disable loop_on_init = True and of course please try to access http://192.168.1.138 and tell me what you see.

Drealine

**Comment by ghost** [comment]
Hi - thanks for getting back to me - If I disable loop_on_init = True the error still occurs.

http://192.168.1.138 returns 

{"data":null,"error":{"code":404,"message":"HTTP Page Not Found"}}

**Comment by Drealine** [comment]
Try this and let me kown what you see :

http://192.168.1.138:80/v1/current_conditions

**Comment by ghost** [comment]
This returns

{"data":{"did":"001D0A712ABB","ts":1686205758,"conditions":[{"lsid":333892,"data_structure_type":1,"txid":1,"temp": 51.8,"hum":76.6,"dew_point": 44.7,"wet_bulb": 47.7,"heat_index": 51.5,"wind_chill": 49.5,"thw_index": 49.2,"thsw_index": 49.8,"wind_speed_last":4.00,"wind_dir_last":83,"wind_speed_avg_last_1_min":6.25,"wind_dir_scalar_avg_last_1_min":80,"wind_speed_avg_last_2_min":6.62,"wind_dir_scalar_avg_last_2_min":83,"wind_speed_hi_last_2_min":9.00,"wind_dir_at_hi_speed_last_2_min":83,"wind_speed_avg_last_10_min":6.62,"wind_dir_scalar_avg_last_10_min":80,"wind_speed_hi_last_10_min":11.00,"wind_dir_at_hi_speed_last_10_min":83,"rain_size":2,"rain_rate_last":0,"rain_rate_hi":0,"rainfall_last_15_min":0,"rain_rate_hi_last_15_min":0,"rainfall_last_60_min":0,"rainfall_last_24_hr":0,"rain_storm":0,"rain_storm_start_at":null,"solar_rad":132,"uv_index":0.0,"rx_state":0,"trans_battery_flag":0,"rainfall_daily":0,"rainfall_monthly":0,"rainfall_year":1003,"rain_storm_last":2,"rain_storm_last_start_at":1685504701,"rain_storm_last_end_at":1685595661},{"lsid":333891,"data_structure_type":4,"temp_in": 67.5,"hum_in":52.0,"dew_point_in": 49.3,"heat_index_in": 66.5},{"lsid":333890,"data_structure_type":3,"bar_sea_level":30.186,"bar_trend":-0.009,"bar_absolute":30.175}]},"error":nul

**Comment by Drealine** [comment]
Ok
Did you manage to stop weewx a while and restart ?
Maybe WLL block request when force requests a lot

**Comment by ghost** [comment]
Let I left it about 5 minutes before restoring WeeWX - the error doe snot seems to affect the normal running so I will just leave it be - thanks for your help

**Comment by Drealine** [comment]
I'm read again all setting, you use wl_archive_enable = 1, so if you not set wl API KEY, it create a connection refused.
Just change to 0 and the error disapear.

**Comment by ghost** [comment]
Hi - thanks for your continued help - if I set wl_archive_enable = 1 then (as I understand it) the archive from Weatherlink.com will not work. I have double checked my settings and I have definitely got the wl_apikey, wl_apisecret and wl_stationid settings correct

**Comment by Drealine** [comment]
On your weewx server, did you try to resolve google.com for example ?

ping google.com

DNS is correct in your config ? What's your OS installation ?

**Comment by ghost** [comment]
ping works fine - WeeWx is running on a Raspberry Pi 4b with then latest Raspbian Desktop

**Comment by Drealine** [comment]
Hm really strange. Seems to be an issue regarding API. Repo not change since 2022, I'll need to rework on it. If you can help me to share json request, it will be nice :)

**Comment by ghost** [comment]
Thanks but I am not sure what “ If you can help me to share json request” means - sorry!

**Comment by Drealine** [comment]
Ok np. I'll add this to task list
