### ISSUE TITLE
Rain during the day not okay

### ISSUE THREAD

**Issue by hoevenvd** [Drealine/weatherlinklive-driver-weewx#9]
I have two environments running weewx. One is production, and one is development. In production I have running the WLL-driver from grebleem, in development the driver from Drealine is running.

There's a big mismatch in reported rain between the two driver. grebleem reports 3.8 mm today (which is correct), drealine reports 1.8 mm.

Below the mysql-output, where you can see a lot of 0.2 mm from column grebleem, and corresponding 0.0 mm from Drealine.

**Daily sum:**
mysql> select sum(round(weewx.archive.rain,1)) as greebleem,sum(round(weewx_import.archive.rain,1)) as drealine from weewx.archive,weewx_import.archive where weewx.archive.datetime=weewx_import.archive.datetime and weewx.archive.rain > 0 and from_unixtime(weewx.archive.datetime) like '2020-10-08%' order by weewx.archive.datetime desc;
+-----------+----------+
| greebleem | drealine |
+-----------+----------+
|       3.8 |      1.8 |
+-----------+----------+
1 row in set (0.28 sec)

**Per row of today where rain > 0 (grebleem):**
mysql> select from_unixtime(weewx.archive.datetime),round(weewx.archive.rain,1) as greebleem,round(weewx_import.archive.rain,1) as drealine from weewx.archive,weewx_import.archive where weewx.archive.datetime=weewx_import.archive.datetime and weewx.archive.rain > 0 and from_unixtime(weewx.archive.datetime) like '2020-10-08%' order by weewx.archive.datetime desc;
+---------------------------------------+-----------+----------+
| from_unixtime(weewx.archive.datetime) | greebleem | drealine |
+---------------------------------------+-----------+----------+
| 2020-10-08 10:45:00                   |       0.2 |      0.2 |
| 2020-10-08 09:56:00                   |       0.2 |      0.0 |
| 2020-10-08 09:24:00                   |       0.2 |      0.0 |
| 2020-10-08 09:08:00                   |       0.2 |      0.0 |
| 2020-10-08 09:00:00                   |       0.2 |      0.0 |
| 2020-10-08 08:49:00                   |       0.2 |      0.0 |
| 2020-10-08 08:43:00                   |       0.2 |      0.0 |
| 2020-10-08 08:37:00                   |       0.2 |      0.0 |
| 2020-10-08 08:25:00                   |       0.2 |      0.0 |
| 2020-10-08 08:17:00                   |       0.2 |      0.0 |
| 2020-10-08 08:08:00                   |       0.2 |      0.0 |
| 2020-10-08 07:56:00                   |       0.2 |      0.2 |
| 2020-10-08 07:44:00                   |       0.2 |      0.2 |
| 2020-10-08 07:31:00                   |       0.2 |      0.2 |
| 2020-10-08 07:17:00                   |       0.2 |      0.2 |
| 2020-10-08 07:12:00                   |       0.2 |      0.2 |
| 2020-10-08 07:01:00                   |       0.2 |      0.2 |
| 2020-10-08 06:51:00                   |       0.2 |      0.2 |
| 2020-10-08 06:42:00                   |       0.2 |      0.2 |
+---------------------------------------+-----------+----------+
19 rows in set (0.26 sec)

**Comment by Drealine** [comment]
Please add logs between specific current time.

**Comment by hoevenvd** [comment]
[syslog.zip](https://github.com/Drealine/weatherlinklive-driver-weewx/files/5347593/syslog.zip)


I'm sorry, but I am giving you the complete syslog of today. I find it difficult to know what piece of information you exactly need. So, instead of cutting and pasting pieces of logging and maybe missing relevant info, I give you the complete log.

**Comment by Drealine** [comment]
There are a problem with your weewx engine.
I saw 2 times current_conditions or realtime_broadcast in log with the same datetime. 

A user told me that they doesn't have problems with realtime enable or not.

**Comment by hoevenvd** [comment]
Hmm, I am not sure what to do now. Accept this error, as it is beyond the scope of this driver? If it is in the weewx engine, I cannot solve that.

**Comment by Drealine** [comment]
Maybe a re-install, or reboot the server also.
But no problems in logs, rain it's good for each time but not in your sql table.

**Comment by hoevenvd** [comment]
Okay, will do that. I will create a fresh new virtual machine, and install weewx from scratch using the repository apt.

Reboot had no effect.

Will let you know how it goes. More rain to come&to test.

**Comment by hoevenvd** [comment]
Complete new install, Ubuntu 20.04, Weewx out-of-the-box, Mysql reconrding records, no additional skins: 100% weewx with WLLDriver. First findings: rain is now okay! How weird and strange, that the weewx-engine was 'broken'. Anyway, I will take a close look the rest of this week, more rain to come.

Thanks Florentin, for taking the time to point at the weewx-engine! I must have done something terrible to break this... :(

**Comment by Drealine** [comment]
> Complete new install, Ubuntu 20.04, Weewx out-of-the-box, Mysql reconrding records, no additional skins: 100% weewx with WLLDriver. First findings: rain is now okay! How weird and strange, that the weewx-engine was 'broken'. Anyway, I will take a close look the rest of this week, more rain to come.
> 
> Thanks Florentin, for taking the time to point at the weewx-engine! I must have done something terrible to break this... :(

Hi !

No problems. I really hope that it will work great after that !

But, like you say, it's very strange that Weewx do that. If for some reasons the bug appear again, please make an issue directly to Weewx. Probably a bug in the engine maybe.

Have a nice day.
